import os
import json
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Any

from apex_quant.config import AppConfig, get_config
from apex_quant.data.point_in_time import PointInTimeAccessor
from apex_quant.ai.client import AppAILLM, extract_json
from apex_quant.backtest.engine import Backtester
from apex_quant.backtest.result import BacktestResult
from apex_quant.risk.types import Direction, Signal
from apex_quant.strategies.base import Strategy
from apex_quant.ml.dataset import compute_feature_frame

class AdaptiveWrapperStrategy(Strategy):
    """
    Wraps any base strategy and passes active trading signals through
    the LLM to check if they violate any rules generated by previous passes.
    """
    def __init__(self, base_strategy: Strategy, rules: list[str], app_url: str):
        self.base = base_strategy
        self.rules = rules
        self.app_url = app_url
        self.llm = AppAILLM()
        self.name = f"adaptive_{base_strategy.name}"
        self.cfg = get_config()
        self._fm: pd.DataFrame | None = None
        self._fm_id: int | None = None

    def _frame(self, pit: PointInTimeAccessor) -> pd.DataFrame:
        if self._fm_id != id(pit):
            self._fm = compute_feature_frame(pit.as_of(pit.end), self.cfg)
            self._fm_id = id(pit)
        return self._fm

    def generate(self, pit: PointInTimeAccessor, t: pd.Timestamp | str, instrument: str = "") -> Signal:
        # Get base strategy signal
        sig = self.base.generate(pit, t, instrument)
        if sig.direction == Direction.FLAT or not self.rules:
            return sig

        # Look up current market state/indicators
        fm = self._frame(pit)
        t_ts = pd.Timestamp(t)
        if t_ts not in fm.index:
            return sig
        
        row = fm.loc[t_ts]
        if row.isna().any():
            return sig
        
        # Build features string for prompt
        features_dict = row.to_dict()
        indicators_str = "\n".join([f"- {k}: {v:.6f}" for k, v in features_dict.items() if np.isfinite(v)])
        
        # Query LLM to verify if trade violates any rules
        prompt = (
            f"Candidate Trade: {sig.direction.value} {instrument} on {t_ts.date()}\n"
            f"Market Indicators at Entry:\n{indicators_str}\n\n"
            f"Active Trading Rules:\n"
            + "\n".join([f"{i+1}. {rule}" for i, rule in enumerate(self.rules)])
            + "\n\nDoes this candidate trade violate any of the rules? Output ONLY a JSON object:\n"
            '{"violates": true/false, "rule_violated": "rule text here if true, else empty"}'
        )
        
        system_prompt = (
            "You are a strict quantitative risk supervisor. Evaluate if the proposed trade "
            "violates any of the active trading rules based on the market indicators. Be conservative. "
            "Only return the raw JSON object."
        )
        
        # Complete via LLM
        res_text = self.llm.complete(prompt, system_prompt, max_tokens=150, temperature=0.1)
        res = extract_json(res_text)
        if res and res.get("violates") is True:
            violated = res.get("rule_violated", "Unknown rule")
            # Override signal to FLAT
            return Signal(
                instrument=instrument,
                direction=Direction.FLAT,
                probability=0.5,
                reward_risk=sig.reward_risk,
                confidence=0.0,
                rationale=f"Vetoed by adaptive rule: {violated}"
            )
        
        return sig


class AdaptiveBacktester:
    def __init__(self, cfg: AppConfig | None = None):
        self.cfg = cfg or get_config()
        self.llm = AppAILLM()
        self.bt = Backtester(self.cfg)

    def run_with_reflection(
        self,
        pit: PointInTimeAccessor,
        base_strategy: Strategy,
        instrument: str,
        *,
        start=None,
        end=None,
        warmup: int = 250,
        rules_path: str = "data_store/adaptive_rules.json",
        max_reflection_rules: int = 10,
    ) -> tuple[BacktestResult, BacktestResult | None, list[str]]:
        
        # Pass 1: Run standard blind backtest
        print("Executing Pass 1 (Blind)...")
        res1 = self.bt.run(pit, base_strategy, instrument, start=start, end=end, warmup=warmup)
        
        # Filter losing trades
        losses = [t for t in res1.trades if t.pnl < 0]
        print(f"Pass 1 complete. Total trades: {len(res1.trades)}, Losses: {len(losses)}, Win Rate: {res1.metrics.get('win_rate', 0.0)*100:.2f}%")
        
        # If win rate is high or no losses, return Pass 1
        if not losses:
            print("No losses to reflect on.")
            return res1, None, []

        # Gather point-in-time features for losing trades
        df_all = pit.as_of(pit.end)
        features_df = compute_feature_frame(df_all, self.cfg)
        
        reflected_trades = []
        # Group or limit losses to reflection batch size (e.g. 15)
        for t in losses[:15]:
            ts = pd.Timestamp(t.entry_time)
            # Find closest feature timestamp
            if ts in features_df.index:
                feat_row = features_df.loc[ts].to_dict()
                feat_str = ", ".join([f"{k}={v:.4f}" for k, v in feat_row.items() if np.isfinite(v)])
                reflected_trades.append({
                    "date": t.entry_time,
                    "direction": t.direction,
                    "exit_reason": t.exit_reason,
                    "pnl": t.pnl,
                    "indicators": feat_str
                })
        
        # Run AI Reflection to generate rules
        rules = []
        if reflected_trades:
            print(f"Sending {len(reflected_trades)} losing trades to AI Critic for post-mortem analysis...")
            prompt = (
                f"Instrument: {instrument}\n"
                f"Losing Trades Log:\n{json.dumps(reflected_trades, indent=2)}\n\n"
                f"Analyze these losses. Identify common technical features, volatility states, or trend regimes "
                f"where the primary strategy failed. Propose up to {max_reflection_rules} strict rules to filter out similar bad entries.\n"
                f"Each rule must refer to the indicator names in the log (e.g., 'mom_21', 'rvol_21', 'trend_slope_200').\n"
                f"Return ONLY a JSON array of strings containing the rules, for example:\n"
                f'["Avoid LONG when trend_slope_200 is negative", "Avoid SHORT when rvol_21 is low"]'
            )
            
            system_prompt = (
                "You are an expert quantitative research critic. Analyze the trade failures "
                "and generate robust, simple, logical filtering rules to improve the strategy's win rate. "
                "Only return the raw JSON array of strings."
            )
            
            res_text = self.llm.complete(prompt, system_prompt, max_tokens=1000, temperature=0.2)
            extracted = extract_json(res_text)
            if isinstance(extracted, list):
                rules = [str(r) for r in extracted]
                print(f"AI Critic generated {len(rules)} adaptive rules:")
                for i, r in enumerate(rules):
                    print(f"  {i+1}. {r}")
            else:
                print("Failed to parse rules from AI Critic response.")

        # Save rules to disk
        if rules:
            # Resolve relative rules_path
            p = Path(rules_path)
            if not p.is_absolute():
                p = Path(self.cfg.data.store_dir) / p
            os.makedirs(p.parent, exist_ok=True)
            with open(p, "w", encoding="utf-8") as f:
                json.dump(rules, f, indent=2)
            print(f"Rules saved to {p}")
        else:
            p = Path(rules_path)
            if not p.is_absolute():
                p = Path(self.cfg.data.store_dir) / p
            if p.exists():
                with open(p, "r", encoding="utf-8") as f:
                    rules = json.load(f)
                print(f"Loaded existing rules from {p}")

        # Pass 2: Run backtest with Adaptive Wrapper Strategy
        res2 = None
        if rules:
            print("\nExecuting Pass 2 (Grounded in Adaptive Rules)...")
            wrapper_strat = AdaptiveWrapperStrategy(base_strategy, rules, self.cfg.ai.app_url)
            res2 = self.bt.run(pit, wrapper_strat, instrument, start=start, end=end, warmup=warmup)
            print(f"Pass 2 complete. Total trades: {len(res2.trades)}, Win Rate: {res2.metrics.get('win_rate', 0.0)*100:.2f}%")
        
        return res1, res2, rules
